spring:
  application:
    name: spring-sql-gradle-producer
    description: A proof-of-concept Spring Data REST & JPA project
    version: "@application.version@"
    timestamp: "@application.buildTimestamp@"
    branch: "@application.branch@"
    environment: ${ENV}
  profiles.active: default
  h2:
    console:
      enabled: true
  datasource:
    driver-class: "org.h2.Driver"
    url: jdbc:h2:mem:test-db
    username:
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: "update"

api:
  basePath: "api/"
  version:
    v1: "v1"
    v2: "v2"

server:
  port: ${SERVER_PORT}
  servlet:
    contextPath: "/${spring.application.name}"

logback:
  appender: ${LOGBACK_APPENDER}
  level: DEBUG
